<template><h1 id="user-management" tabindex="-1"><a class="header-anchor" href="#user-management" aria-hidden="true">#</a> User management</h1>
<p>EventStoreDB allows managing users programmatically using the .NET client. This guide covers details about default users, groups and managing users.</p>
<h2 id="default-users" tabindex="-1"><a class="header-anchor" href="#default-users" aria-hidden="true">#</a> Default users</h2>
<p>By default EventStoreDB has two users <code>admin</code> and <code>ops</code> with the password <code>changeit</code>.</p>
<div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>We recommend you create separate functional account with minimal access rights for any connected application or service.</p>
</div>
<h2 id="default-groups" tabindex="-1"><a class="header-anchor" href="#default-groups" aria-hidden="true">#</a> Default groups</h2>
<p>By default EventStoreDB has two user groups <code>$admins</code> <code>$ops</code>. However it is possible to create custom groups with the .NET client.</p>
<h2 id="user-management-1" tabindex="-1"><a class="header-anchor" href="#user-management-1" aria-hidden="true">#</a> User management</h2>
<p>The EventStoreDB .NET client includes helper methods that use the HTTP API to allow for the management of users. This section describes the methods found in the <code>UsersManager</code> class. All methods in this class are asynchronous.</p>
<h3 id="create-usersmanager-instance" tabindex="-1"><a class="header-anchor" href="#create-usersmanager-instance" aria-hidden="true">#</a> Create UsersManager instance</h3>
<p>@[code](clients/dotnet/21.2/sample-code/DotNetClient/UsersCreateUsersManager.cs#UserManager</p>
<p>Resolving the host name may be especially useful if the EventStoreDB Admin UI is not available under loopback address e.g., when container orchestrator assign dynamic DNS based on service name.</p>
<h3 id="create-a-user" tabindex="-1"><a class="header-anchor" href="#create-a-user" aria-hidden="true">#</a> Create a user</h3>
<p>Creates a user, the credentials for this operation must be a member of the <code>$admins</code> group.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token keyword">public</span> <span class="token return-type class-name">Task</span> <span class="token function">CreateUserAsync</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> login<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span></span> fullName<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span><span class="token punctuation">[</span><span class="token punctuation">]</span></span> groups<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span></span> password<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="disable-a-user" tabindex="-1"><a class="header-anchor" href="#disable-a-user" aria-hidden="true">#</a> Disable a user</h3>
<p>Disables a user, the credentials for this operation must be a member of the <code>$admins</code> group.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token keyword">public</span> <span class="token return-type class-name">Task</span> <span class="token function">DisableAsync</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> login<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="enable-a-user" tabindex="-1"><a class="header-anchor" href="#enable-a-user" aria-hidden="true">#</a> Enable a User</h3>
<p>Enables a user, the credentials for this operation must be a member of the <code>$admins</code> group.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token keyword">public</span> <span class="token return-type class-name">Task</span> <span class="token function">EnableAsync</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> login<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="delete-a-user" tabindex="-1"><a class="header-anchor" href="#delete-a-user" aria-hidden="true">#</a> Delete a user</h3>
<p>Deletes (non-recoverable) a user, the credentials for this operation must be a member of the <code>$admins</code> group. If you prefer this action to be recoverable, disable the user as opposed to deleting the user.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token keyword">public</span> <span class="token return-type class-name">Task</span> <span class="token function">DeleteUserAsync</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> login<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="list-all-users" tabindex="-1"><a class="header-anchor" href="#list-all-users" aria-hidden="true">#</a> List all users</h3>
<p>Lists all users.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token keyword">public</span> <span class="token return-type class-name">Task<span class="token punctuation">&lt;</span>List<span class="token punctuation">&lt;</span>UserDetails<span class="token punctuation">></span><span class="token punctuation">></span></span> <span class="token function">ListAllAsync</span><span class="token punctuation">(</span><span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="get-details-of-user" tabindex="-1"><a class="header-anchor" href="#get-details-of-user" aria-hidden="true">#</a> Get details of user</h3>
<p>Return the details of the user supplied in user credentials (e.g. the user making the request).</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token keyword">public</span> <span class="token return-type class-name">Task<span class="token punctuation">&lt;</span>UserDetails<span class="token punctuation">></span></span> <span class="token function">GetCurrentUserAsync</span><span class="token punctuation">(</span><span class="token class-name">UserCredentials</span> userCredentials<span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="get-details-of-logged-in-user" tabindex="-1"><a class="header-anchor" href="#get-details-of-logged-in-user" aria-hidden="true">#</a> Get details of logged in user</h3>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token keyword">public</span> <span class="token return-type class-name">Task<span class="token punctuation">&lt;</span>UserDetails<span class="token punctuation">></span></span> <span class="token function">GetUserAsync</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> login<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials<span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="update-user-details-manage-user-groups" tabindex="-1"><a class="header-anchor" href="#update-user-details-manage-user-groups" aria-hidden="true">#</a> Update user details / manage user groups</h3>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token keyword">public</span> <span class="token return-type class-name">Task</span> <span class="token function">UpdateUserAsync</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> login<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span></span> fullName<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span><span class="token punctuation">[</span><span class="token punctuation">]</span></span> groups<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>Although <code>UsersManager</code> does not have separate methods for idempotent adding/removing user groups it can be extended:</p>
<p>@[code](clients/dotnet/21.2/sample-code/DotNetClient/UsersManagerExtensions.cs#Extensions</p>
<h3 id="reset-user-password" tabindex="-1"><a class="header-anchor" href="#reset-user-password" aria-hidden="true">#</a> Reset user password</h3>
<p>Resets the password of a user. The credentials for this operation must be part of the <code>$admins</code> group.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token keyword">public</span> <span class="token return-type class-name">Task</span> <span class="token function">ResetPasswordAsync</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> login<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span></span> newPassword<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div></template>
