version: '3.4'

services:
  eventstore.db1:
    image: docker.pkg.github.com/eventstore/eventstore/eventstore:20.6.1-alpha.0.40-buster-slim
    environment:
      - EVENTSTORE_WORKER_THREADS=5
      - EVENTSTORE_CLUSTER_SIZE=3
      - EVENTSTORE_CLUSTER_GOSSIP_PORT=2113
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_DISCOVER_VIA_DNS=true
      - EVENTSTORE_CLUSTER_DNS=eventstore.local
      - EVENTSTORE_INT_IP=172.42.238.3
      - EVENTSTORE_EXT_IP=172.42.238.3
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    networks:
      app_net:
        aliases:
          - eventstore.local
        ipv4_address: 172.42.238.3
    volumes:
      - type: volume
        source: eventstore-volume-data1
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs1
        target: /var/log/eventstore

  eventstore.db2:
    image: docker.pkg.github.com/eventstore/eventstore/eventstore:20.6.1-alpha.0.40-buster-slim
    environment:
      - EVENTSTORE_WORKER_THREADS=5
      - EVENTSTORE_CLUSTER_SIZE=3
      - EVENTSTORE_CLUSTER_GOSSIP_PORT=2113
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_DISCOVER_VIA_DNS=true
      - EVENTSTORE_CLUSTER_DNS=eventstore.local
      - EVENTSTORE_INT_IP=172.42.238.4
      - EVENTSTORE_EXT_IP=172.42.238.4
      - EVENTSTORE_INSECURE=true
    expose:
      - "1113"
      - "2113"
    networks:
      app_net:
        aliases:
          - eventstore.local
        ipv4_address: 172.42.238.4
    volumes:
      - type: volume
        source: eventstore-volume-data2
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs2
        target: /var/log/eventstore

  eventstore.db3:
    image: docker.pkg.github.com/eventstore/eventstore/eventstore:20.6.1-alpha.0.40-buster-slim
    environment:
      - EVENTSTORE_WORKER_THREADS=5
      - EVENTSTORE_CLUSTER_SIZE=3
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_CLUSTER_GOSSIP_PORT=2113
      - EVENTSTORE_DISCOVER_VIA_DNS=true
      - EVENTSTORE_CLUSTER_DNS=eventstore.local
      - EVENTSTORE_INT_IP=172.42.238.5
      - EVENTSTORE_EXT_IP=172.42.238.5
      - EVENTSTORE_INSECURE=true
    expose:
      - "1113"
      - "2113"
    networks:
      app_net:
        aliases:
          - eventstore.local
        ipv4_address: 172.42.238.5
    volumes:
      - type: volume
        source: eventstore-volume-data3
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs3
        target: /var/log/eventstore

volumes:
  eventstore-volume-data1:
  eventstore-volume-logs1:
  eventstore-volume-data2:
  eventstore-volume-logs2:
  eventstore-volume-data3:
  eventstore-volume-logs3:

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.42.238.0/24"
