<template><h1 id="deleting-a-stream" tabindex="-1"><a class="header-anchor" href="#deleting-a-stream" aria-hidden="true">#</a> Deleting a stream</h1>
<h2 id="soft-delete" tabindex="-1"><a class="header-anchor" href="#soft-delete" aria-hidden="true">#</a> Soft delete</h2>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task<span class="token punctuation">&lt;</span>DeleteResult<span class="token punctuation">></span></span> <span class="token function">DeleteStreamAsync</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> stream<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">long</span></span> expectedVersion<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><!-- TODO: Need a better explanation -->
<p>By default when you delete a stream, EventStoreDB soft deletes it. You can recreate the stream by appending new events to it. If you try to read a soft deleted stream you receive an error response.</p>
<h2 id="hard-delete" tabindex="-1"><a class="header-anchor" href="#hard-delete" aria-hidden="true">#</a> Hard Delete</h2>
<p>You can hard delete a stream.</p>
<div class="custom-container warning"><p class="custom-container-title">WARNING</p>
<p>A hard delete is permanent and the stream is not removed during a scavenge. If you hard delete a stream, you cannot recreate the stream.</p>
</div>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task<span class="token punctuation">&lt;</span>DeleteResult<span class="token punctuation">></span></span> <span class="token function">DeleteStreamAsync</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> stream<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">long</span></span> expectedVersion<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">bool</span></span> hardDelete<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div></template>
