<template><h1 id="projections" tabindex="-1"><a class="header-anchor" href="#projections" aria-hidden="true">#</a> Projections</h1>
<p>This page provides an example of using <RouterLink to="/server/generated/v5/docs/projections/#types-of-projections">user-defined projections</RouterLink> in your application.</p>
<h2 id="adding-sample-data" tabindex="-1"><a class="header-anchor" href="#adding-sample-data" aria-hidden="true">#</a> Adding sample data</h2>
<p>Download the following files that contain sample data used throughout this step of the getting started guide.</p>
<ul>
<li><a href="/server/generated/v5/samples/http-api/data/shoppingCart-b989fe21-9469-4017-8d71-9820b8dd1164.json">shoppingCart-b989fe21-9469-4017-8d71-9820b8dd1164.json</a></li>
<li><a href="/server/generated/v5/samples/http-api/data/shoppingCart-b989fe21-9469-4017-8d71-9820b8dd1165.json">shoppingCart-b989fe21-9469-4017-8d71-9820b8dd1165.json</a></li>
<li><a href="/server/generated/v5/samples/http-api/data/shoppingCart-b989fe21-9469-4017-8d71-9820b8dd1166.json">shoppingCart-b989fe21-9469-4017-8d71-9820b8dd1166.json</a></li>
<li><a href="/server/generated/v5/samples/http-api/data/shoppingCart-b989fe21-9469-4017-8d71-9820b8dd1167.json">shoppingCart-b989fe21-9469-4017-8d71-9820b8dd1167.json</a></li>
</ul>
<p>Add the sample data to four different streams:
First, we need a function to read JSON files and construct the list of <code>EventData</code> instances:</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token return-type class-name">List<span class="token punctuation">&lt;</span>EventData<span class="token punctuation">></span></span> <span class="token function">ReadEvents</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> filePath<span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    <span class="token class-name"><span class="token keyword">var</span></span> events    <span class="token operator">=</span> JsonConvert<span class="token punctuation">.</span><span class="token generic-method"><span class="token function">DeserializeObject</span><span class="token generic class-name"><span class="token punctuation">&lt;</span><span class="token keyword">dynamic</span><span class="token punctuation">></span></span></span><span class="token punctuation">(</span>File<span class="token punctuation">.</span><span class="token function">ReadAllText</span><span class="token punctuation">(</span>filePath<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token class-name"><span class="token keyword">var</span></span> eventData <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">List<span class="token punctuation">&lt;</span>EventData<span class="token punctuation">></span></span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token keyword">foreach</span> <span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">var</span></span> @<span class="token keyword">event</span> <span class="token keyword">in</span> events<span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        <span class="token class-name"><span class="token keyword">var</span></span> id        <span class="token operator">=</span> @<span class="token keyword">event</span><span class="token punctuation">.</span>eventId<span class="token punctuation">.</span><span class="token function">ToString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token class-name"><span class="token keyword">var</span></span> eventType <span class="token operator">=</span> @<span class="token keyword">event</span><span class="token punctuation">.</span>eventType<span class="token punctuation">.</span><span class="token function">ToString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

        eventData<span class="token punctuation">.</span><span class="token function">Add</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token constructor-invocation class-name">EventData</span><span class="token punctuation">(</span>Guid<span class="token punctuation">.</span><span class="token function">Parse</span><span class="token punctuation">(</span>id<span class="token punctuation">)</span><span class="token punctuation">,</span> eventType<span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">,</span> Encoding<span class="token punctuation">.</span>UTF8<span class="token punctuation">.</span><span class="token function">GetBytes</span><span class="token punctuation">(</span>@<span class="token keyword">event</span><span class="token punctuation">.</span>data<span class="token punctuation">.</span><span class="token function">ToString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">return</span> eventData<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br></div></div><p>Then, we can use this function and push events to EventStoreDB:</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token keyword">foreach</span> <span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">var</span></span> f <span class="token keyword">in</span> Directory<span class="token punctuation">.</span><span class="token function">GetFiles</span><span class="token punctuation">(</span><span class="token string">"../"</span><span class="token punctuation">,</span> <span class="token string">"shoppingCart-*"</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    <span class="token class-name"><span class="token keyword">var</span></span> streamName     <span class="token operator">=</span> Path<span class="token punctuation">.</span><span class="token function">GetFileNameWithoutExtension</span><span class="token punctuation">(</span>f<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token class-name"><span class="token keyword">var</span></span> step3EventData <span class="token operator">=</span> <span class="token function">ReadEvents</span><span class="token punctuation">(</span>f<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token class-name"><span class="token keyword">var</span></span> eventData      <span class="token operator">=</span> step3EventData<span class="token punctuation">.</span><span class="token function">ToArray</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">await</span> conn<span class="token punctuation">.</span><span class="token function">AppendToStreamAsync</span><span class="token punctuation">(</span>streamName<span class="token punctuation">,</span> ExpectedVersion<span class="token punctuation">.</span>Any<span class="token punctuation">,</span> eventData<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><h2 id="creating-your-first-projection" tabindex="-1"><a class="header-anchor" href="#creating-your-first-projection" aria-hidden="true">#</a> Creating your first projection</h2>
<div class="custom-container tip"><p class="custom-container-title">Next steps</p>
<p>Read <RouterLink to="/server/generated/v5/docs/projections/user-defined-projections.html">this guide</RouterLink> to find out more about the user defined projection's API.</p>
</div>
<p>The projection counts the number of 'XBox One S's that customers added to their shopping carts.</p>
<p>A projection starts with a selector, in this case <code>fromAll()</code>. Another possibility is <code>fromCategory({category})</code> which this step discusses later, but for now, <code>fromAll</code> should do.</p>
<p>The second part of a projection is a set of filters. There is a special filter called <code>$init</code> that sets up an initial state. You want to start a counter from 0 and each time EventStoreDB observes an <code>ItemAdded</code> event for an 'Xbox One S,' increment the counter.</p>
<p>Here is the projection code:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>File not found<span class="token operator">!</span></code></pre><div class="line-numbers"></div></div><p>You create a projection by calling the projection API and providing it with the definition of the projection. Here you decide how to run the projection, declaring that you want the projection to start from the beginning and keep running.</p>
<p>You can send the projection code as text along the other parameters, using the <code>ProjectionsManager</code> instance:</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token class-name"><span class="token keyword">var</span></span> projectionsManager <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">ProjectionsManager</span><span class="token punctuation">(</span>
    <span class="token named-parameter punctuation">log</span><span class="token punctuation">:</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">ConsoleLogger</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token named-parameter punctuation">httpEndPoint</span><span class="token punctuation">:</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">IPEndPoint</span><span class="token punctuation">(</span>IPAddress<span class="token punctuation">.</span><span class="token function">Parse</span><span class="token punctuation">(</span><span class="token string">"127.0.0.1"</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token number">2113</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token named-parameter punctuation">operationTimeout</span><span class="token punctuation">:</span> TimeSpan<span class="token punctuation">.</span><span class="token function">FromMilliseconds</span><span class="token punctuation">(</span><span class="token number">5000</span><span class="token punctuation">)</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token keyword">const</span> <span class="token class-name"><span class="token keyword">string</span></span> countItemsProjection <span class="token operator">=</span> <span class="token string">@"
    fromAll().when({
        $init: function(){
            return {
                count: 0
            }
        },
        ItemAdded: function(s,e){
            if(e.body.Description.indexOf('Xbox One S') >= 0){
                s.count += 1;
            }
        }
    })"</span><span class="token punctuation">;</span>
<span class="token keyword">await</span> projectionsManager<span class="token punctuation">.</span><span class="token function">CreateContinuousAsync</span><span class="token punctuation">(</span><span class="token string">"xbox-one-s-counter"</span><span class="token punctuation">,</span> countItemsProjection<span class="token punctuation">,</span> adminCredentials<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br></div></div><div class="custom-container tip"><p class="custom-container-title">Next steps</p>
<p><a href="#projections-management">Read here</a> for more information on creating projections with the .NET API and the parameters available, or <RouterLink to="/server/generated/v5/docs/projections/">our projections section</RouterLink> for details on projection syntax.</p>
</div>
<h2 id="querying-projection-state" tabindex="-1"><a class="header-anchor" href="#querying-projection-state" aria-hidden="true">#</a> Querying projection state</h2>
<p>Now the projection is running, you can query the state of the projection. As this projection has a single state, query it with the following request:</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token class-name"><span class="token keyword">var</span></span> projectionState <span class="token operator">=</span> <span class="token keyword">await</span> projectionsManager<span class="token punctuation">.</span><span class="token function">GetStateAsync</span><span class="token punctuation">(</span><span class="token string">"xbox-one-s-counter"</span><span class="token punctuation">,</span> adminCredentials<span class="token punctuation">)</span><span class="token punctuation">;</span>
Console<span class="token punctuation">.</span><span class="token function">WriteLine</span><span class="token punctuation">(</span>projectionState<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h4 id="querying-projection-state-by-partition" tabindex="-1"><a class="header-anchor" href="#querying-projection-state-by-partition" aria-hidden="true">#</a> Querying projection state by partition</h4>
<p>You can partition the projection state to only include some events for aggregating the state rather than processing all the events. Querying with partitions because you have to specify the partition and the name of the stream.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token class-name"><span class="token keyword">var</span></span> projectionState <span class="token operator">=</span> <span class="token keyword">await</span> projectionsManager<span class="token punctuation">.</span><span class="token function">GetPartitionStateAsync</span><span class="token punctuation">(</span>
    <span class="token named-parameter punctuation">name</span><span class="token punctuation">:</span> <span class="token string">"shopping-cart-item-counter"</span><span class="token punctuation">,</span>
    <span class="token named-parameter punctuation">partitionId</span><span class="token punctuation">:</span> <span class="token string">"shoppingCart-b989fe21-9469-4017-8d71-9820b8dd1164"</span><span class="token punctuation">,</span>
    <span class="token named-parameter punctuation">userCredentials</span><span class="token punctuation">:</span> adminCredentials
<span class="token punctuation">)</span><span class="token punctuation">;</span>
Console<span class="token punctuation">.</span><span class="token function">WriteLine</span><span class="token punctuation">(</span>projectionState<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><p>The server then returns the state for the partition:</p>
<div class="language-json ext-json line-numbers-mode"><pre v-pre class="language-json"><code>File not found!</code></pre><div class="line-numbers"></div></div><h2 id="emitting-new-events" tabindex="-1"><a class="header-anchor" href="#emitting-new-events" aria-hidden="true">#</a> Emitting new events</h2>
<p>The above gives you the correct result but requires you to poll for the state of a projection. What if you wanted EventStoreDB to notify you about state updates via subscriptions?</p>
<h3 id="output-state" tabindex="-1"><a class="header-anchor" href="#output-state" aria-hidden="true">#</a> Output state</h3>
<p>Update the projection to output the state to a stream by calling the <code>outputState()</code> method on the projection which by default produces a <code>$projections-{projection-name}-result</code> stream.</p>
<p>Below is the updated projection:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>File not found<span class="token operator">!</span></code></pre><div class="line-numbers"></div></div><p>To update the projection, edit the projection definition with the following request:</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token class-name"><span class="token keyword">var</span></span> projectionsManager <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">ProjectionsManager</span><span class="token punctuation">(</span>
    <span class="token named-parameter punctuation">log</span><span class="token punctuation">:</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">ConsoleLogger</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token named-parameter punctuation">httpEndPoint</span><span class="token punctuation">:</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">IPEndPoint</span><span class="token punctuation">(</span>IPAddress<span class="token punctuation">.</span><span class="token function">Parse</span><span class="token punctuation">(</span><span class="token string">"127.0.0.1"</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token number">2113</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token named-parameter punctuation">operationTimeout</span><span class="token punctuation">:</span> TimeSpan<span class="token punctuation">.</span><span class="token function">FromMilliseconds</span><span class="token punctuation">(</span><span class="token number">5000</span><span class="token punctuation">)</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token keyword">const</span> <span class="token class-name"><span class="token keyword">string</span></span> countItemsProjectionUpdate <span class="token operator">=</span> <span class="token string">@"
    fromAll()
        .when({
            $init: function(){
                return {
                    count: 0
                }
            },
        ItemAdded: function(s,e){
            if(e.body.Description.indexOf('Xbox One S') >= 0){
                s.count += 1;
            }
        }
    }).outputState()"</span><span class="token punctuation">;</span>

<span class="token keyword">await</span> projection<span class="token punctuation">.</span><span class="token function">UpdateQueryAsync</span><span class="token punctuation">(</span><span class="token string">"xbox-one-s-counter"</span><span class="token punctuation">,</span> countItemsProjectionUpdate<span class="token punctuation">,</span> adminCredentials<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br></div></div><p>Then reset the projection you created above:</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token keyword">await</span> projection<span class="token punctuation">.</span><span class="token function">ResetAsync</span><span class="token punctuation">(</span><span class="token string">"xbox-one-s-counter"</span><span class="token punctuation">,</span> adminCredentials<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>You should get a response similar to the one below:</p>
<p>You can now read the events in the result stream by issuing a read request.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token class-name"><span class="token keyword">var</span></span> readEvents <span class="token operator">=</span> <span class="token keyword">await</span> conn<span class="token punctuation">.</span><span class="token function">ReadStreamEventsForwardAsync</span><span class="token punctuation">(</span><span class="token string">"$projections-xbox-one-s-counter-result"</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">foreach</span> <span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">var</span></span> evt <span class="token keyword">in</span> readEvents<span class="token punctuation">.</span>Events<span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    Console<span class="token punctuation">.</span><span class="token function">WriteLine</span><span class="token punctuation">(</span>Encoding<span class="token punctuation">.</span>UTF8<span class="token punctuation">.</span><span class="token function">GetString</span><span class="token punctuation">(</span>evt<span class="token punctuation">.</span>Event<span class="token punctuation">.</span>Data<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><h2 id="configuring-projections" tabindex="-1"><a class="header-anchor" href="#configuring-projections" aria-hidden="true">#</a> Configuring projections</h2>
<p>You can configure properties of the projection by updating values of the <code>options</code> object. For example, the following projection changes the name of the results stream:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>File not found<span class="token operator">!</span></code></pre><div class="line-numbers"></div></div><p>Then send the update to the projection:</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token class-name"><span class="token keyword">var</span></span> projectionsManager <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">ProjectionsManager</span><span class="token punctuation">(</span>
    <span class="token named-parameter punctuation">log</span><span class="token punctuation">:</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">ConsoleLogger</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token named-parameter punctuation">httpEndPoint</span><span class="token punctuation">:</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">IPEndPoint</span><span class="token punctuation">(</span>IPAddress<span class="token punctuation">.</span><span class="token function">Parse</span><span class="token punctuation">(</span><span class="token string">"127.0.0.1"</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token number">2113</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token named-parameter punctuation">operationTimeout</span><span class="token punctuation">:</span> TimeSpan<span class="token punctuation">.</span><span class="token function">FromMilliseconds</span><span class="token punctuation">(</span><span class="token number">5000</span><span class="token punctuation">)</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token keyword">const</span> <span class="token class-name"><span class="token keyword">string</span></span> optionsProjectionOptionsUpdate <span class="token operator">=</span> <span class="token string">@"
    options({ resultStreamName: 'xboxes' })
    fromAll()
        .when({
        $init: function(){
            return {
                count: 0
            }
        },
        ItemAdded: function(s,e){
            if(e.body.Description.indexOf('Xbox One S') >= 0){
                s.count += 1;
            }
        }
    }).outputState()"</span><span class="token punctuation">;</span>

<span class="token keyword">await</span> projection<span class="token punctuation">.</span><span class="token function">UpdateQueryAsync</span><span class="token punctuation">(</span><span class="token string">"xbox-one-s-counter"</span><span class="token punctuation">,</span> optionsProjectionOptionsUpdate<span class="token punctuation">,</span> adminCredentials<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br></div></div><div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>You can find all the options available in the <RouterLink to="/server/generated/v5/docs/projections/user-defined-projections.html">user defined projections guide</RouterLink>.</p>
</div>
<p>Now you can read the result as above, but use the new stream name:</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code>readEvents <span class="token operator">=</span> <span class="token keyword">await</span> conn<span class="token punctuation">.</span><span class="token function">ReadStreamEventsForwardAsync</span><span class="token punctuation">(</span><span class="token string">"xboxes"</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">foreach</span> <span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">var</span></span> evt <span class="token keyword">in</span> readEvents<span class="token punctuation">.</span>Events<span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    Console<span class="token punctuation">.</span><span class="token function">WriteLine</span><span class="token punctuation">(</span>Encoding<span class="token punctuation">.</span>UTF8<span class="token punctuation">.</span><span class="token function">GetString</span><span class="token punctuation">(</span>evt<span class="token punctuation">.</span>Event<span class="token punctuation">.</span>Data<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><h4 id="example-number-of-items-per-shopping-cart" tabindex="-1"><a class="header-anchor" href="#example-number-of-items-per-shopping-cart" aria-hidden="true">#</a> Example: number of items per shopping cart</h4>
<p>The example in this step so far relied on a global state for the projection, but what if you wanted a count of the number of items in the shopping cart per shopping cart.</p>
<p>EventStoreDB has a built-in <code>$by_category</code> projection that lets you select events from a particular list of streams. Enable this projection with the following command.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token class-name"><span class="token keyword">var</span></span> projectionsManager <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">ProjectionsManager</span><span class="token punctuation">(</span>
    <span class="token named-parameter punctuation">log</span><span class="token punctuation">:</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">ConsoleLogger</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token named-parameter punctuation">httpEndPoint</span><span class="token punctuation">:</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">IPEndPoint</span><span class="token punctuation">(</span>IPAddress<span class="token punctuation">.</span><span class="token function">Parse</span><span class="token punctuation">(</span><span class="token string">"127.0.0.1"</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token number">2113</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token named-parameter punctuation">operationTimeout</span><span class="token punctuation">:</span> TimeSpan<span class="token punctuation">.</span><span class="token function">FromMilliseconds</span><span class="token punctuation">(</span><span class="token number">5000</span><span class="token punctuation">)</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token keyword">await</span> projectionsManager<span class="token punctuation">.</span><span class="token function">EnableAsync</span><span class="token punctuation">(</span><span class="token string">"$by_category"</span><span class="token punctuation">,</span> adminCredentials<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>The projection links events from existing streams to new streams by splitting the stream name by a separator. You can configure the projection to specify the position of where to split the stream <code>id</code> and provide a separator.</p>
<p>By default, the category splits the stream <code>id</code> by a dash. The category is the first string.</p>
<table>
<thead>
<tr>
<th>Stream Name</th>
<th>Category</th>
</tr>
</thead>
<tbody>
<tr>
<td>shoppingCart-54</td>
<td>shoppingCart</td>
</tr>
<tr>
<td>shoppingCart-v1-54</td>
<td>shoppingCart</td>
</tr>
<tr>
<td>shoppingCart</td>
<td><em>No category as there is no separator</em></td>
</tr>
</tbody>
</table>
<p>You want to define a projection that produces a count per stream for a category, but the state needs to be per stream. To do so, use <code>$by_category</code> and its <code>fromCategory</code> API method.</p>
<p>Below is the projection:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>File not found<span class="token operator">!</span></code></pre><div class="line-numbers"></div></div><p>Create the projection with the following request:</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token keyword">const</span> <span class="token class-name"><span class="token keyword">string</span></span> itemCounterProjection <span class="token operator">=</span> <span class="token string">@"
    fromCategory('shoppingCart')
        .foreachStream()
        .when({
            $init: function(){
                return {
                    count: 0
                }
            },
            ItemAdded: function(s,e){
                s.count += 1;
            }
        })"</span><span class="token punctuation">;</span>

<span class="token keyword">await</span> projectionsManager<span class="token punctuation">.</span><span class="token function">CreateContinuousAsync</span><span class="token punctuation">(</span>
    <span class="token named-parameter punctuation">name</span><span class="token punctuation">:</span> <span class="token string">"shopping-cart-item-counter"</span><span class="token punctuation">,</span>
    <span class="token named-parameter punctuation">query</span><span class="token punctuation">:</span> itemCounterProjection<span class="token punctuation">,</span>
    <span class="token named-parameter punctuation">trackEmittedStreams</span><span class="token punctuation">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
    <span class="token named-parameter punctuation">userCredentials</span><span class="token punctuation">:</span> adminCredentials
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br></div></div><h2 id="managing-projections" tabindex="-1"><a class="header-anchor" href="#managing-projections" aria-hidden="true">#</a> Managing projections</h2>
<p>The EventStoreDB Client API includes helper methods that use the HTTP API to allow you to manage projections. This document describes the methods found in the <code>ProjectionsManager</code> class. All methods in this class are asynchronous.</p>
<h3 id="enable-a-projection" tabindex="-1"><a class="header-anchor" href="#enable-a-projection" aria-hidden="true">#</a> Enable a projection</h3>
<p>Enables an existing projection by name. You must have access to a projection to enable it.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task</span> <span class="token function">EnableAsync</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> name<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="disable-a-projection" tabindex="-1"><a class="header-anchor" href="#disable-a-projection" aria-hidden="true">#</a> Disable a projection</h3>
<p>Disables an existing projection by name. You must have access to a projection to disable it.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task</span> <span class="token function">DisableAsync</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> name<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="abort-a-projection" tabindex="-1"><a class="header-anchor" href="#abort-a-projection" aria-hidden="true">#</a> Abort a projection</h3>
<p>Aborts an existing projection by name. You must have access to a projection to abort it.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task</span> <span class="token function">AbortAsync</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> name<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="create-a-one-time-projection" tabindex="-1"><a class="header-anchor" href="#create-a-one-time-projection" aria-hidden="true">#</a> Create a one-time projection</h3>
<p>Creates a projection that runs until the end of the log and then stops. The query parameter contains the JavaScript you want created as a one time projection.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task</span> <span class="token function">CreateOneTimeAsync</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> query<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="create-a-continuous-projection" tabindex="-1"><a class="header-anchor" href="#create-a-continuous-projection" aria-hidden="true">#</a> Create a continuous projection</h3>
<p>Creates a projection that runs until the end of the log and then continues running. The query parameter contains the JavaScript you want created as a one time projection. Continuous projections have explicit names and you can enable or disable them via this name.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task</span> <span class="token function">CreateContinuousAsync</span><span class="token punctuation">(</span>
    <span class="token class-name"><span class="token keyword">string</span></span> name<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span></span> query<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><h3 id="list-all-projections" tabindex="-1"><a class="header-anchor" href="#list-all-projections" aria-hidden="true">#</a> List all projections</h3>
<p>Returns a list of all projections.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task<span class="token punctuation">&lt;</span>List<span class="token punctuation">&lt;</span>ProjectionDetails<span class="token punctuation">></span><span class="token punctuation">></span></span> <span class="token function">ListAllAsync</span><span class="token punctuation">(</span><span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="list-one-time-projections" tabindex="-1"><a class="header-anchor" href="#list-one-time-projections" aria-hidden="true">#</a> List one-time projections</h3>
<p>Returns a list of all One-Time Projections.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task<span class="token punctuation">&lt;</span>List<span class="token punctuation">&lt;</span>ProjectionDetails<span class="token punctuation">></span><span class="token punctuation">></span></span> <span class="token function">ListOneTimeAsync</span><span class="token punctuation">(</span><span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="get-statistics-on-a-projection" tabindex="-1"><a class="header-anchor" href="#get-statistics-on-a-projection" aria-hidden="true">#</a> Get statistics on a projection</h3>
<p>Returns the statistics associated with a named projection.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task<span class="token punctuation">&lt;</span><span class="token keyword">string</span><span class="token punctuation">></span></span> <span class="token function">GetStatisticsAsync</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> name<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="delete-projection" tabindex="-1"><a class="header-anchor" href="#delete-projection" aria-hidden="true">#</a> Delete projection</h3>
<p>Deletes a named projection. You must have access to a projection to delete it.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task</span> <span class="token function">DeleteAsync</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> name<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="get-state" tabindex="-1"><a class="header-anchor" href="#get-state" aria-hidden="true">#</a> Get state</h3>
<p>Retrieves the state of a projection.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task<span class="token punctuation">&lt;</span><span class="token keyword">string</span><span class="token punctuation">></span></span> <span class="token function">GetState</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> name<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="get-partition-state" tabindex="-1"><a class="header-anchor" href="#get-partition-state" aria-hidden="true">#</a> Get partition state</h3>
<p>Retrieves the state of the projection via the given partition.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task<span class="token punctuation">&lt;</span><span class="token keyword">string</span><span class="token punctuation">></span></span> <span class="token function">GetPartitionStateAsync</span><span class="token punctuation">(</span>
    <span class="token class-name"><span class="token keyword">string</span></span> name<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span></span> partition<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><h3 id="get-result" tabindex="-1"><a class="header-anchor" href="#get-result" aria-hidden="true">#</a> Get result</h3>
<p>Retrieves the result of the projection.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task<span class="token punctuation">&lt;</span><span class="token keyword">string</span><span class="token punctuation">></span></span> <span class="token function">GetResult</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> name<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="get-partition-result" tabindex="-1"><a class="header-anchor" href="#get-partition-result" aria-hidden="true">#</a> Get partition result</h3>
<p>Retrieves the result of the projection via the given partition.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task<span class="token punctuation">&lt;</span><span class="token keyword">string</span><span class="token punctuation">></span></span> <span class="token function">GetPartitionResultAsync</span><span class="token punctuation">(</span>
    <span class="token class-name"><span class="token keyword">string</span></span> name<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span></span> partition<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div></template>
