<template><p><img src="@source/resources/articles/images/getting-started-with-v1-java-grpc-client/getting-started-with-v1-java-grpc-client-1.svg" alt="cover"></p>
<p>The first release of EventStoreDB gRPC happened on 23rd November 2020, one day after my birthday. If you're a JVM developer, I have a gift for you. I proudly announce the v1 release!</p>
<p>The last few months have been busy. We were working hard to align both the feature set and naming conventions between the gRPC clients. If you were a preview version user, you might find some breaking API changes, but it should be stable from now on.</p>
<p>The Java client supports all Java versions from 8. You can use it also in Scala, Kotlin and Groovy.</p>
<h3 id="installation" tabindex="-1"><a class="header-anchor" href="#installation" aria-hidden="true">#</a> Installation</h3>
<p>To use the gRPC client package, you need to install it either with Maven:</p>
<div class="language-xml ext-xml line-numbers-mode"><pre v-pre class="language-xml"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>dependency</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>groupId</span><span class="token punctuation">></span></span>com.eventstore<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>groupId</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>artifactId</span><span class="token punctuation">></span></span>db-client-java<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>artifactId</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>version</span><span class="token punctuation">></span></span>1.0<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>version</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>dependency</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><p>Scala SBT</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>libraryDependencies <span class="token operator">+=</span> <span class="token string">"com.eventstore"</span> % <span class="token string">"db-client-java"</span> % <span class="token string">"1.0"</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>Gradle Groovy:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>libraryDependencies <span class="token operator">+=</span> <span class="token string">"com.eventstore"</span> % <span class="token string">"db-client-java"</span> % <span class="token string">"1.0"</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>or Gradle Kotlin:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>implementation<span class="token punctuation">(</span><span class="token string">"com.eventstore:db-client-java:1.0"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="connecting-to-the-db-server" tabindex="-1"><a class="header-anchor" href="#connecting-to-the-db-server" aria-hidden="true">#</a> Connecting to the DB server</h3>
<p>EventStoreDB is cross-platform, and you can run it natively on your OS. However, the easiest way to get started with a local setup is running it with Docker.</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>docker run --name esdb-node -it -p <span class="token number">2113</span>:2113 -p <span class="token number">1113</span>:1113 <span class="token punctuation">\</span>
  eventstore/eventstore:latest --insecure --run-projections<span class="token operator">=</span>All
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>After that, you should have the single-node EventStoreDB setup, and you can connect with the gRPC client.</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token class-name">EventStoreDBClientSettings</span> settings <span class="token operator">=</span> 	       <span class="token class-name">EventStoreDBConnectionString</span><span class="token punctuation">.</span><span class="token function">parse</span><span class="token punctuation">(</span><span class="token string">"esdb://localhost:2113?tls=false"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token class-name">EventStoreDBClient</span> client <span class="token operator">=</span> <span class="token class-name">EventStoreDBClient</span><span class="token punctuation">.</span><span class="token function">create</span><span class="token punctuation">(</span>settings<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>You may notice <span style="font-style: italic;">&quot;?tls=false&quot;</span> and <span style="font-style: italic;">&quot;--insecure&quot;</span> params in the setup. EventStoreDB is secure-by-default. Those settings allow connecting without using the HTTPS/TLS setup. Using this setting is okay for the local dev environment but should not be used on production. For detailed instructions check the <a href="https://developers.eventstore.com/server/v20/server/installation/" target="_blank" rel="noopener noreferrer">installation guide<OutboundLink/></a> and <a href="https://developers.eventstore.com/server/v20/server/security/#protocol-security" target="_blank" rel="noopener noreferrer">security recommendations<OutboundLink/></a>.</p>
<h3 id="working-with-events" tabindex="-1"><a class="header-anchor" href="#working-with-events" aria-hidden="true">#</a> Working with Events</h3>
<p>The centrepiece of EventStoreDB are operations on events. Following the Event Sourcing principles, you could use it to keep the application's state a series of events. The event should be recorded as a result of each business operation.</p>
<p>Multiple series of events are called streams. You can represent the entity as the sequence of events (state mutations) correlated by the entity id. In Event Sourcing, the entity state is rebuilt by reading all stream events and applying them one by one in order of appearance.</p>
<p>I'll use the cinema ticket reservation example and Java. However, our API is also compatible with Scala, Kotlin and Groovy.</p>
<p>You can append events by:</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token class-name">String</span> userId <span class="token operator">=</span> <span class="token string">"ms_smith"</span><span class="token punctuation">;</span>
<span class="token class-name">String</span> movieId <span class="token operator">=</span> <span class="token string">"homealone"</span><span class="token punctuation">;</span>
<span class="token class-name">String</span> seatId <span class="token operator">=</span> <span class="token string">"seat1"</span><span class="token punctuation">;</span>
<span class="token class-name">String</span> reservationId <span class="token operator">=</span> <span class="token class-name">String</span><span class="token punctuation">.</span><span class="token function">format</span><span class="token punctuation">(</span>res_<span class="token operator">%</span>s_<span class="token operator">%</span>s<span class="token punctuation">,</span> movieId<span class="token punctuation">,</span> seatId<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token class-name">SeatReserved</span> event <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">SeatReserved</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
event<span class="token punctuation">.</span><span class="token function">setReservationId</span><span class="token punctuation">(</span>reservationId<span class="token punctuation">)</span><span class="token punctuation">;</span>
event<span class="token punctuation">.</span><span class="token function">setMovieId</span><span class="token punctuation">(</span>movieId <span class="token punctuation">)</span><span class="token punctuation">;</span>
event<span class="token punctuation">.</span>setSeatId <span class="token punctuation">(</span>seatId<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token class-name">EventData</span> eventData <span class="token operator">=</span> <span class="token class-name">EventData</span>
    <span class="token punctuation">.</span><span class="token function">builderAsJson</span><span class="token punctuation">(</span><span class="token string">"SeatReserved"</span><span class="token punctuation">,</span> event<span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">build</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

client<span class="token punctuation">.</span><span class="token function">appendToStream</span><span class="token punctuation">(</span><span class="token string">"some-stream"</span><span class="token punctuation">,</span> eventData<span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br></div></div><p>At first, we're setting up the event data, then wrapping it using EventData class. EventStoreDB allows serialising data in JSON and binary format. EventData provides builder methods to make that easier. We're using <a href="https://github.com/FasterXML/jackson" target="_blank" rel="noopener noreferrer">Jackson<OutboundLink/></a> internally for serialisation.</p>
<p>gRPC client operations are returning the <a href="https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Future.html" target="_blank" rel="noopener noreferrer">Future<OutboundLink/></a> because of their asynchronous nature.</p>
<p>For reading events, you have two options.</p>
<ol>
<li>Reading from the stream: this method is typically used for reading the entity state. You can read streams forwards or backwards, and even read from a specific position. Additional read options can be set through the options class.</li>
</ol>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token class-name">ReadStreamOptions</span> options <span class="token operator">=</span> <span class="token class-name">ReadStreamOptions</span><span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">forwards</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">fromStart</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token class-name">ReadResult</span> result <span class="token operator">=</span> client<span class="token punctuation">.</span><span class="token function">readStream</span><span class="token punctuation">(</span><span class="token string">"some-stream"</span><span class="token punctuation">,</span> options<span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token class-name">List</span> events <span class="token operator">=</span> result<span class="token punctuation">.</span><span class="token function">getEvents</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div><p>You don't need to provide all options explicitly. If you're okay with using the default options, then you can call the read method without them. This call will be identical to the one above:</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token class-name">ReadResult</span> result <span class="token operator">=</span> client<span class="token punctuation">.</span><span class="token function">readStream</span><span class="token punctuation">(</span><span class="token string">"some-stream"</span><span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token class-name">List</span> events <span class="token operator">=</span> result<span class="token punctuation">.</span><span class="token function">getEvents</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p>We use the same pattern in other methods.</p>
<ol start="2">
<li>Reading from all stream: EventStoreDB underneath is an append-only log. This log is also known as the <em>$all</em> stream. All events are added there one after another in the order of occurrence. Thanks to that, EventStoreDB can keep the events global ordering. You're getting events across the streams in the order as they were added by reading from it.</li>
</ol>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token keyword">long</span> maxCount <span class="token operator">=</span> <span class="token number">10</span><span class="token punctuation">;</span>

<span class="token class-name">ReadResult</span> result <span class="token operator">=</span> client<span class="token punctuation">.</span><span class="token function">readAll</span><span class="token punctuation">(</span>maxCount<span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token class-name">List</span> events <span class="token operator">=</span> result<span class="token punctuation">.</span><span class="token function">getEvents</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><h3 id="subscribing-to-the-streams" tabindex="-1"><a class="header-anchor" href="#subscribing-to-the-streams" aria-hidden="true">#</a> Subscribing to the streams</h3>
<p>One of the most significant advantages of Event-Driven Architecture is observability. Each action in the system triggers an event. The event gathers business information about the fact registered in the system. This is a simple but powerful feature: it allows modelling the complex business workflows by splitting the work into smaller chunks. Having that, we achieve loosely coupled architecture.</p>
<p>EventStoreDB provides the subscription functionality to enable that. You can subscribe to the single stream:</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token class-name">SubscriptionListener</span> listener <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">SubscriptionListener</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token annotation punctuation">@Override</span>
    <span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">onEvent</span><span class="token punctuation">(</span><span class="token class-name">Subscription</span> subscription<span class="token punctuation">,</span> <span class="token class-name">ResolvedEvent</span> event<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"Received event"</span>
            <span class="token operator">+</span> event<span class="token punctuation">.</span><span class="token function">getOriginalEvent</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">getStreamRevision</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token operator">+</span> <span class="token string">"@"</span> <span class="token operator">+</span> event<span class="token punctuation">.</span><span class="token function">getOriginalEvent</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">getStreamId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token class-name">HandleEvent</span><span class="token punctuation">(</span>event<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
client<span class="token punctuation">.</span><span class="token function">subscribeToStream</span><span class="token punctuation">(</span><span class="token string">"some-stream"</span><span class="token punctuation">,</span> listener<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><p>or to the <em>$all</em> stream:</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token class-name">SubscriptionListener</span> listener <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">SubscriptionListener</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token annotation punctuation">@Override</span>
    <span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">onEvent</span><span class="token punctuation">(</span><span class="token class-name">Subscription</span> subscription<span class="token punctuation">,</span> <span class="token class-name">ResolvedEvent</span> event<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"Received event"</span>
            <span class="token operator">+</span> event<span class="token punctuation">.</span><span class="token function">getOriginalEvent</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">getStreamRevision</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">getValueUnsigned</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token operator">+</span> <span class="token string">"@"</span> <span class="token operator">+</span> event<span class="token punctuation">.</span><span class="token function">getOriginalEvent</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">getStreamId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token class-name">HandleEvent</span><span class="token punctuation">(</span>event<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
client<span class="token punctuation">.</span><span class="token function">subscribeToAll</span><span class="token punctuation">(</span>listener<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><p>You'll get an asynchronous notification about each appended event through <em>SubscriptionListener</em> callback method. This enables you to:</p>
<ul>
<li>update your read model(s) based on the event data,</li>
<li>pipe the notification into the external queuing systems like RabbitMQ, Kafka.</li>
</ul>
<p>The neat feature of EventStoreDB subscriptions is that you can filter them by e.g. event type, stream prefix, regex. You can get only notifications about the events that you’re interested in. Filtering will happen on the server-side, so it’s also a potential performance improvement.</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token class-name">SubscriptionListener</span> listener <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">SubscriptionListener</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token annotation punctuation">@Override</span>
    <span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">onEvent</span><span class="token punctuation">(</span><span class="token class-name">Subscription</span> subscription<span class="token punctuation">,</span> <span class="token class-name">ResolvedEvent</span> event<span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token function">handle</span><span class="token punctuation">(</span>event<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token class-name">String</span> reservationStreamPrefix <span class="token operator">=</span> <span class="token string">"res"</span><span class="token punctuation">;</span>

<span class="token class-name">SubscriptionFilter</span> filter <span class="token operator">=</span> <span class="token class-name">SubscriptionFilter</span><span class="token punctuation">.</span><span class="token function">newBuilder</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">withStreamNamePrefix</span><span class="token punctuation">(</span>reservationStreamPrefix<span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">build</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token class-name">SubscribeToAllOptions</span> options <span class="token operator">=</span> <span class="token class-name">SubscribeToAllOptions</span><span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">filter</span><span class="token punctuation">(</span>filter<span class="token punctuation">)</span><span class="token punctuation">;</span>

client<span class="token punctuation">.</span><span class="token function">subscribeToAll</span><span class="token punctuation">(</span>
    listener<span class="token punctuation">,</span>
    options
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br></div></div><h3 id="source-code-and-documentation" tabindex="-1"><a class="header-anchor" href="#source-code-and-documentation" aria-hidden="true">#</a> Source code and documentation</h3>
<p>Java gRPC client is Open Sourced and available under Apache 2.0 License in the <a href="https://github.com/EventStore/EventStoreDB-Client-Java/" target="_blank" rel="noopener noreferrer">GitHub Repository<OutboundLink/></a>. You can find <a href="https://developers.eventstore.com/clients/grpc/getting-started?codeLanguage=Java" target="_blank" rel="noopener noreferrer">detailed documentation and samples here<OutboundLink/></a>. We value the Open Source community. Feel free to send us Pull Requests, Issues or other forms of contribution. If you have more questions, <a href="https://discuss.eventstore.com" target="_blank" rel="noopener noreferrer">we're available and happy to help on our Discuss forum<OutboundLink/></a>.</p>
</template>
