<template><h1 id="persistent-subscriptions-monitoring" tabindex="-1"><a class="header-anchor" href="#persistent-subscriptions-monitoring" aria-hidden="true">#</a> Persistent subscriptions monitoring</h1>
<p>The Client API includes helper methods that wrap the HTTP API to allow you to monitor persistent subscriptions. This page describes the methods found in the <code>PersistentSubscriptionsManager</code> class. All methods in this class are asynchronous.</p>
<h2 id="create-the-manager-instance" tabindex="-1"><a class="header-anchor" href="#create-the-manager-instance" aria-hidden="true">#</a> Create the manager instance</h2>
<p>Before accessing any of the methods described below, you need to create an instance of the <code>PersistentSubscriptionsManager</code> class. It needs a logger instance and one of the variations of the <code>EndPoint</code> abstract class. You would normally use either the <code>IpEndPoint</code> or <code>DnsEndPoint</code>. Since all HTTP calls would be redirected to the cluster leader, you can use an IP address of any cluster node. When using the <code>DnsEndPoint</code>, you can specify the DNS name of the cluster.</p>
<p>For example:</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token class-name"><span class="token keyword">var</span></span> subscriptionManager <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">PersistentSubscriptionsManager</span><span class="token punctuation">(</span>
    <span class="token keyword">new</span> <span class="token constructor-invocation class-name">ConsoleLogger</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token keyword">new</span> <span class="token constructor-invocation class-name">DnsEndPoint</span><span class="token punctuation">(</span><span class="token string">"esdb.acme.org"</span><span class="token punctuation">,</span> <span class="token number">2113</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    TimeSpan<span class="token punctuation">.</span><span class="token function">FromSeconds</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><p>Notice that you need to specify the HTTP port that your application can reach. Most probably you'd need to use the external HTTP port, which is <code>2113</code> by default.</p>
<h2 id="get-all-persistent-subscriptions-from-all-streams" tabindex="-1"><a class="header-anchor" href="#get-all-persistent-subscriptions-from-all-streams" aria-hidden="true">#</a> Get all persistent subscriptions from all streams</h2>
<p>Returns information about all persistent subscriptions from all streams.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token keyword">public</span> <span class="token return-type class-name">Task</span> <span class="token function">List</span><span class="token punctuation">(</span><span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h2 id="get-persistent-subscriptions-for-a-stream" tabindex="-1"><a class="header-anchor" href="#get-persistent-subscriptions-for-a-stream" aria-hidden="true">#</a> Get persistent subscriptions for a stream</h2>
<p>Returns information about the persistent subscription for a stream you specify with <code>stream</code>. You must have access to the stream.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token keyword">public</span> <span class="token return-type class-name">Task</span> <span class="token function">List</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> stream<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h2 id="get-persistent-subscription-for-a-stream" tabindex="-1"><a class="header-anchor" href="#get-persistent-subscription-for-a-stream" aria-hidden="true">#</a> Get persistent subscription for a stream</h2>
<p>Gets the details of the persistent subscription <code>subscriptionName</code> on <code>stream</code>. You must have access to the persistent subscription and the stream.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token keyword">public</span> <span class="token return-type class-name">Task</span> <span class="token function">Describe</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> stream<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span></span> subscriptionName<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div></template>
