<template><h1 id="security" tabindex="-1"><a class="header-anchor" href="#security" aria-hidden="true">#</a> Security</h1>
<p>EventStoreDB supports basic authentication for HTTP API and TCP calls, and supports access control lists (ACL) for streams.</p>
<h2 id="authentication-and-authorization" tabindex="-1"><a class="header-anchor" href="#authentication-and-authorization" aria-hidden="true">#</a> Authentication and authorization</h2>
<p>EventStoreDB supports basic HTTP authentication to internal users. You create and manage these users with the RESTful API or the Admin UI. Read more in the <RouterLink to="/server/generated/v5/docs/http-api/api/#create-a-user">users management guide</RouterLink>. Once you have added users, you can use their details with HTTP requests or native client's authorization process.</p>
<p>Alternatively you can also use the 'trusted intermediary' header for externalized authentication that allows you to integrate almost any authentication system with EventStoreDB. Read more about <RouterLink to="/server/generated/v5/docs/security/trusted-intermediary.html">the trusted intermediary header</RouterLink>.</p>
<p>If you were to use the wrong user or no user when connecting to EventStoreDB, you receive a <code>401 Unauthorized</code> response for HTTP API or Exception for native client.</p>
<div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>Remember to change the default password for default users and disable unused users after the cluster setup is complete.</p>
</div>
<h2 id="secure-eventstoredb-node" tabindex="-1"><a class="header-anchor" href="#secure-eventstoredb-node" aria-hidden="true">#</a> Secure EventStoreDB node</h2>
<p>We recommend you run EventStoreDB over TLS to encrypt the user information. <RouterLink to="/server/generated/v5/docs/security/ssl-linux.html">Read this guide for instructions</RouterLink>. If you are running the clustered version you can also setup TLS for the replication protocol.</p>
<div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>We recommend using the latest TLS version instead of SSL <a href="https://en.wikipedia.org/wiki/Transport_Layer_Security#SSL_1.0,_2.0,_and_3.0" target="_blank" rel="noopener noreferrer">explanation available here<OutboundLink/></a>. All references to SSL in documentation or code are there for only historical reasons and will be replaced with TLS in the future.</p>
</div>
<div class="custom-container warning"><p class="custom-container-title">WARNING</p>
<p>Avoid exposing EventStoreDB to the global internet network.</p>
</div>
<h2 id="user-management" tabindex="-1"><a class="header-anchor" href="#user-management" aria-hidden="true">#</a> User management</h2>
<p>The EventStoreDB .NET client includes helper methods that use the HTTP API to allow for the management of users. This section describes the methods found in the <code>UsersManager</code> class. All methods in this class are asynchronous.</p>
<h3 id="default-users" tabindex="-1"><a class="header-anchor" href="#default-users" aria-hidden="true">#</a> Default users</h3>
<p>By default, EventStoreDB has two users <code>admin</code> and <code>ops</code> with the password <code>changeit</code>.</p>
<div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>We recommend you create separate functional account with minimal access rights for any connected application or service.</p>
</div>
<h3 id="default-groups" tabindex="-1"><a class="header-anchor" href="#default-groups" aria-hidden="true">#</a> Default groups</h3>
<p>By default, EventStoreDB has two user groups <code>$admins</code> <code>$ops</code>. However, it is possible to create custom groups with the .NET client.</p>
<h3 id="create-usersmanager-instance" tabindex="-1"><a class="header-anchor" href="#create-usersmanager-instance" aria-hidden="true">#</a> Create UsersManager instance</h3>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token class-name"><span class="token keyword">var</span></span> hostInfo <span class="token operator">=</span> Dns<span class="token punctuation">.</span><span class="token function">GetHostEntry</span><span class="token punctuation">(</span><span class="token string">"localhost"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token class-name"><span class="token keyword">var</span></span> manager <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">UsersManager</span><span class="token punctuation">(</span>
    <span class="token keyword">new</span> <span class="token constructor-invocation class-name">ConsoleLogger</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token keyword">new</span> <span class="token constructor-invocation class-name">IPEndPoint</span><span class="token punctuation">(</span>hostInfo<span class="token punctuation">.</span>AddressList<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token number">2113</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    TimeSpan<span class="token punctuation">.</span><span class="token function">FromSeconds</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><p>Resolving the host name may be especially useful if the EventStoreDB Admin UI is not available under loopback address e.g., when container orchestrator assign dynamic DNS based on service name.</p>
<h3 id="create-a-user" tabindex="-1"><a class="header-anchor" href="#create-a-user" aria-hidden="true">#</a> Create a user</h3>
<p>Creates a user, the credentials for this operation must be a member of the <code>$admins</code> group.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task</span> <span class="token function">CreateUserAsync</span><span class="token punctuation">(</span>
    <span class="token class-name"><span class="token keyword">string</span></span> login<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span></span> fullName<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span><span class="token punctuation">[</span><span class="token punctuation">]</span></span> groups<span class="token punctuation">,</span> 
    <span class="token class-name"><span class="token keyword">string</span></span> password<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h3 id="disable-a-user" tabindex="-1"><a class="header-anchor" href="#disable-a-user" aria-hidden="true">#</a> Disable a user</h3>
<p>Disables a user, the credentials for this operation must be a member of the <code>$admins</code> group.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task</span> <span class="token function">DisableAsync</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> login<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="enable-a-user" tabindex="-1"><a class="header-anchor" href="#enable-a-user" aria-hidden="true">#</a> Enable a User</h3>
<p>Enables a user, the credentials for this operation must be a member of the <code>$admins</code> group.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task</span> <span class="token function">EnableAsync</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> login<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="delete-a-user" tabindex="-1"><a class="header-anchor" href="#delete-a-user" aria-hidden="true">#</a> Delete a user</h3>
<p>Deletes (non-recoverable) a user, the credentials for this operation must be a member of the <code>$admins</code> group. If you prefer this action to be recoverable, disable the user as opposed to deleting the user.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task</span> <span class="token function">DeleteUserAsync</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> login<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="list-all-users" tabindex="-1"><a class="header-anchor" href="#list-all-users" aria-hidden="true">#</a> List all users</h3>
<p>Use this method to get a list of all users in the cluster.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task<span class="token punctuation">&lt;</span>List<span class="token punctuation">&lt;</span>UserDetails<span class="token punctuation">></span><span class="token punctuation">></span></span> <span class="token function">ListAllAsync</span><span class="token punctuation">(</span><span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="get-user-details" tabindex="-1"><a class="header-anchor" href="#get-user-details" aria-hidden="true">#</a> Get user details</h3>
<p>Return the details of the user supplied in user credentials (e.g. the user making the request).</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task<span class="token punctuation">&lt;</span>UserDetails<span class="token punctuation">></span></span> <span class="token function">GetCurrentUserAsync</span><span class="token punctuation">(</span><span class="token class-name">UserCredentials</span> userCredentials<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="get-details-of-logged-in-user" tabindex="-1"><a class="header-anchor" href="#get-details-of-logged-in-user" aria-hidden="true">#</a> Get details of logged-in user</h3>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task<span class="token punctuation">&lt;</span>UserDetails<span class="token punctuation">></span></span> <span class="token function">GetUserAsync</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> login<span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> userCredentials<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="update-user-details-and-groups" tabindex="-1"><a class="header-anchor" href="#update-user-details-and-groups" aria-hidden="true">#</a> Update user details and groups</h3>
<p>Although <code>UsersManager</code> does not have separate methods for idempotent adding/removing user groups it can be extended:</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token keyword">class</span> <span class="token class-name">UsersManagerExtensions</span>
<span class="token punctuation">{</span>
    <span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token keyword">async</span> <span class="token return-type class-name">Task</span> <span class="token function">AddUserToGroupAsync</span><span class="token punctuation">(</span><span class="token keyword">this</span> <span class="token class-name">UsersManager</span> usersManager<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span></span> userLogin<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span></span> <span class="token keyword">group</span><span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> credentials<span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        <span class="token class-name"><span class="token keyword">var</span></span> user   <span class="token operator">=</span> <span class="token keyword">await</span> usersManager<span class="token punctuation">.</span><span class="token function">GetUserAsync</span><span class="token punctuation">(</span>userLogin<span class="token punctuation">,</span> credentials<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token class-name"><span class="token keyword">var</span></span> groups <span class="token operator">=</span> user<span class="token punctuation">.</span>Groups<span class="token punctuation">.</span><span class="token function">ToList</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>groups<span class="token punctuation">.</span><span class="token function">Contains</span><span class="token punctuation">(</span><span class="token keyword">group</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token keyword">return</span><span class="token punctuation">;</span>

        groups<span class="token punctuation">.</span><span class="token function">Add</span><span class="token punctuation">(</span><span class="token keyword">group</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">await</span> usersManager<span class="token punctuation">.</span><span class="token function">UpdateUserAsync</span><span class="token punctuation">(</span>user<span class="token punctuation">.</span>LoginName<span class="token punctuation">,</span> user<span class="token punctuation">.</span>FullName<span class="token punctuation">,</span> groups<span class="token punctuation">.</span><span class="token function">ToArray</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> credentials<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token keyword">async</span> <span class="token return-type class-name">Task</span> <span class="token function">RemoveUserFromGroupAsync</span><span class="token punctuation">(</span><span class="token keyword">this</span> <span class="token class-name">UsersManager</span> usersManager<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span></span> userLogin<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span></span> <span class="token keyword">group</span><span class="token punctuation">,</span> <span class="token class-name">UserCredentials</span> credentials<span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        <span class="token class-name"><span class="token keyword">var</span></span> user   <span class="token operator">=</span> <span class="token keyword">await</span> usersManager<span class="token punctuation">.</span><span class="token function">GetUserAsync</span><span class="token punctuation">(</span>userLogin<span class="token punctuation">,</span> credentials<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token class-name"><span class="token keyword">var</span></span> groups <span class="token operator">=</span> user<span class="token punctuation">.</span>Groups<span class="token punctuation">.</span><span class="token function">ToList</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>groups<span class="token punctuation">.</span><span class="token function">Contains</span><span class="token punctuation">(</span><span class="token keyword">group</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token keyword">return</span><span class="token punctuation">;</span>

        groups<span class="token punctuation">.</span><span class="token function">Remove</span><span class="token punctuation">(</span><span class="token keyword">group</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">await</span> usersManager<span class="token punctuation">.</span><span class="token function">UpdateUserAsync</span><span class="token punctuation">(</span>user<span class="token punctuation">.</span>LoginName<span class="token punctuation">,</span> user<span class="token punctuation">.</span>FullName<span class="token punctuation">,</span> groups<span class="token punctuation">.</span><span class="token function">ToArray</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> credentials<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br></div></div><div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task</span> <span class="token function">UpdateUserAsync</span><span class="token punctuation">(</span>
    <span class="token class-name"><span class="token keyword">string</span></span> login<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span></span> fullName<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span><span class="token punctuation">[</span><span class="token punctuation">]</span></span> groups<span class="token punctuation">,</span> 
    <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h3 id="reset-user-password" tabindex="-1"><a class="header-anchor" href="#reset-user-password" aria-hidden="true">#</a> Reset user password</h3>
<p>Resets the password of a user. The credentials for this operation must be part of the <code>$admins</code> group.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token return-type class-name">Task</span> <span class="token function">ResetPasswordAsync</span><span class="token punctuation">(</span>
    <span class="token class-name"><span class="token keyword">string</span></span> login<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span></span> newPassword<span class="token punctuation">,</span> 
    <span class="token class-name">UserCredentials</span> userCredentials <span class="token operator">=</span> <span class="token keyword">null</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h2 id="access-control-lists" tabindex="-1"><a class="header-anchor" href="#access-control-lists" aria-hidden="true">#</a> Access control lists</h2>
<p>Alongside authentication, EventStoreDB supports per stream configuration of Access Control Lists (ACL). To configure the ACL of a stream go to its head and look for the <code>metadata</code> relationship link to fetch the metadata for the stream.</p>
<p>For more information on the structure of Access Control Lists read <RouterLink to="/server/generated/v5/docs/security/users-and-access-control-lists.html">Access Control Lists</RouterLink>.</p>
<h3 id="acl-example" tabindex="-1"><a class="header-anchor" href="#acl-example" aria-hidden="true">#</a> ACL example</h3>
<p>The ACL below gives <code>writer</code> read and write permission on the stream, while <code>reader</code> has read permission on the stream. Only users in the <code>$admins</code> group can delete the stream or read and write the metadata.</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token class-name"><span class="token keyword">var</span></span> metadata <span class="token operator">=</span> StreamMetadata<span class="token punctuation">.</span><span class="token function">Build</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">SetCustomPropertyWithValueAsRawJsonString</span><span class="token punctuation">(</span>
        <span class="token string">"customRawJson"</span><span class="token punctuation">,</span>
        <span class="token string">@"{
            ""$acl"": {
                ""$w"": ""writer"",
                ""$r"": [
                    ""reader"",
                    ""also-reader""
                ],
                ""$d"": ""$admins"",
                ""$mw"": ""$admins"",
                ""$mr"": ""$admins""
            }
        }"</span>
    <span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">await</span> connection<span class="token punctuation">.</span><span class="token function">SetStreamMetadataAsync</span><span class="token punctuation">(</span>
    streamName<span class="token punctuation">,</span> 
    ExpectedVersion<span class="token punctuation">.</span>Any<span class="token punctuation">,</span> 
    metadata<span class="token punctuation">,</span> 
    adminCredentials
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br></div></div></template>
